### PR TITLE
Backport yahoo patch v24.1

### PR DESCRIPTION
**Pull request by stieg**
Ports the Yahoo fix back to v24 of extension so users of Gnome Shell v42 (Ubuntu 22.04 LTS) can have this extension work for them.

@cinatic Suggest you create a v24 branch on your repo and I can target that for this merge if you like.  Or just merge this in as you see fit.  I based this commit off of v22 since that was the closest one I could base it off of.  There are really only 2 commits here, the cherry-pick and the version bump commit.  LMK how you want to proceed.

### CODE REVIEW

**Comment by stieg** [comment]
*bump*

**Comment by cinatic** [comment]
hey, thanks for your effort. At the first glance this looks very good, I would like to run it on some test distros, then I will merge it (not sure about the name yet)

**Comment by cinatic** [comment]
release has been created https://github.com/cinatic/stocks-extension/releases/tag/v24.1

**Comment by BirdOfChaos** [comment]
I didn't see that @stieg had submitted this PR, so I replicated the work today (except that I started from v24.1 instead of v22). It's not all wasted, I learned some things. 
@cinatic, the fact that I was able to start from 24.1 shows that there is a problem with that tag. It doesn't have the changes from [v24_fixed_yahoo_api](https://github.com/cinatic/stocks-extension/tree/v24_fixed_yahoo_api) in it. It looks like the tag was made from v20.

**Pull request merged**
